---
canonical_url_base: https://djseltzer.com
timezone: America/Los_Angeles
markdown: kramdown
exclude:
  - README.txt
  - run.sh
sass:
  style: compressed
compress_html:
  comments: all
plugins:
  - jekyll-sitemap