---
title: davidseltzer.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 
baseurl: 
url: 
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
